// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SogongTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sogong() {
    driver.get("http://ticket.interpark.com/");
    driver.manage().window().setSize(new Dimension(1531, 1039));
    driver.findElement(By.cssSelector(".btn_musical")).click();
    driver.findElement(By.cssSelector(".prds img")).click();
    driver.findElement(By.linkText("판매정보")).click();
    js.executeScript("window.scrollTo(0,2000)");
    driver.findElement(By.linkText("이용후기448")).click();
    js.executeScript("window.scrollTo(0,869)");
    driver.findElement(By.linkText("기대평17")).click();
    js.executeScript("window.scrollTo(0,869)");
    driver.findElement(By.cssSelector("li:nth-child(28)")).click();
    driver.findElement(By.linkText("3회 11:00")).click();
    driver.findElement(By.cssSelector(".is-primary > span")).click();
  }
}
